AllCops:
  Exclude:
    - 'db/migrate/*'
    - 'db/schema.rb'
  RunRailsCops: true

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
